# escape=`

# framework 4.8 image
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install .NET Core SDK
ENV DOTNET_CORE_VERSION 6.0.400

RUN Invoke-WebRequest `
        -UseBasicParsing `
        -Uri https://dot.net/v1/dotnet-install.ps1 `
        -OutFile dotnet-install.ps1; `
    ./dotnet-install.ps1 `
        -InstallDir '/Program Files/dotnet' `
        -Version $env:DOTNET_CORE_VERSION; `
    Remove-Item -Force dotnet-install.ps1;

# Install VS Build Tools
RUN Invoke-WebRequest `
        -UseBasicParsing `
        -Uri https://aka.ms/vs/17/release/vs_buildtools.exe `
        -OutFile vs_buildtools.exe; `
    $process = Start-Process -FilePath vs_buildtools.exe `
	    -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", "--installPath", """""""""C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools""""""""", `
        "--add", "Microsoft.VisualStudio.Workload.DataBuildTools", `
        "--add", "Microsoft.Net.Component.4.7.2.Sdk", `
        "--add", "Microsoft.Net.Component.4.7.2.TargetingPack", `
        "--add", "Microsoft.Net.ComponentGroup.TargetingPacks.Common", `
        "--add", "Microsoft.VisualStudio.Component.Roslyn.Compiler", `
        "--add", "Microsoft.VisualStudio.Component.Roslyn.LanguageServices", `
        "--add", "Microsoft.VisualStudio.Component.SQL.SSDTBuildSku" `
		-Wait -PassThru ; `
    Remove-Item -Force vs_buildtools.exe;

# Install DAC
RUN Write-Host 'Downloading DACFX...'; `
    Invoke-WebRequest -Uri 'https://aka.ms/dacfx-msi' -OutFile 'DacFramework.msi'; `
    Write-Host 'Installing DACFX...'; `
    Start-Process -Wait -Passthru -FilePath 'msiexec.exe' -ArgumentList '/qn /norestart /i DacFramework.msi'; `
    Write-Host 'Removing ...'; `
    Remove-Item DacFramework.msi -Force; `
    Write-Host 'Complete.'

ENV SQLDBExtensionsRefPath="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v17.0\SSDT"
ENV SSDTPath="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\Microsoft\SQLDB\Dac\160"

# We cannot use a short var for path due to windows env limitations, https://github.com/moby/moby/issues/30033
ENV PATH="C:\\Windows\\system32;C:\\Windows;C:\\BuildTools\\MSBuild\\Current\\Bin;C:\\Program Files\\dotnet;C:\\Program Files\\powershell;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin"

CMD ["dotnet", "msbuild"]
