name: "Build and test - all"
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  build-and-test:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build database
        run: >-
          docker run
          --rm
          --name dotnet_build
          --workdir /src
          --volume ${{ github.workspace }}\src:c:\src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          msbuild Data/IntegrationTesting.Data.Sql/IntegrationTesting.Data.Sql.sqlproj -p:Configuration=Release
      - name: Build application code
        run: >-
          docker run
          --rm
          --name dotnet_build
          --workdir /src
          --volume ${{ github.workspace }}\src:c:\src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          powershell dir "*.csproj" -Recurse | Where {$PSItem.FullName -notlike "*Tests.csproj"} | %{dotnet build  $PSItem.FullName --configuration Release}
      - name: Build test code
        run: >-
          docker run
          --rm
          --name dotnet_build
          --workdir /src
          --volume ${{ github.workspace }}\src:c:\src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          powershell dir "*Tests.csproj" -Recurse | %{dotnet build  $PSItem.FullName --configuration Release --no-dependencies}
