name: "Build and test - all"
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build dacpac
        run: >-
          docker run
          --rm
          --name dotnet_build
          --workdir /src
          --volume ${{ github.workspace }}\src:c:\src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          msbuild Data/IntegrationTesting.Data.Sql/IntegrationTesting.Data.Sql.sqlproj -p:Configuration=Release
      - name: Build application and test code
        run: >-
          docker run
          --rm
          --name dotnet_build
          --workdir /src
          --volume ${{ github.workspace }}\src:c:\src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          dotnet build  Data/IntegrationTesting.Data.Tests/IntegrationTesting.Data.Tests.csproj --configuration Release
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: src/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: src/
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.400
      - name: Test
        run: dotnet test Data/IntegrationTesting.Data.Tests/IntegrationTesting.Data.Tests.csproj --no-build --verbosity normal
