name: "Build and test - all"
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    # paths:
    #   - 'src/**'

jobs:
  build-and-test:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: >-
          docker run
          --name dotnet_test
          --workdir /src
          --volume ${{ github.workspace }}/src:/src
          ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
          dotnet test IntegrationTesting.sln
