name: Sqltools docker image build and publish

on:
  push:
    branches: [main]
    paths:
      - 'docker/sqltools/**'
  pull_request:
    paths:
      - 'docker/sqltools/**'

jobs:
  build-and-push-docker-image:
    name: Build sqltools docker image and push to GitHub package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push your image to Azure Container Registry 
      - name: Build and Push container to ACR
        run: |
          docker build --file=docker/sqltools/sockerfile -t ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest .
          docker push ghcr.io/benchiverton/dotnet.integrationtesting/sqltools:latest
